version: "3.6"

services:
  app1:
    container_name: analytics1
    build: .
    ports:
      - "${HOST_PORT:-18081}:8081"
    restart: always
    networks:
      - db
    depends_on:
      - clickhouse

  # app2:
  #   container_name: analytics2
  #   build: .
  #   ports:
  #     - "${HOST_PORT:-18082}:8082"
  #   restart: always

  # app3:
  #   container_name: analytics3
  #   build: .
  #   ports:
  #     - "${HOST_PORT:-18083}:8083"
  #   restart: always

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.3.2.23-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: always
    networks:
      - db
    volumes:
      - clickhouse:/data/clickhouse

networks:
  db:
    driver: bridge

volumes:
    clickhouse: